name: TEST-NG-01

on:
  workflow_dispatch:

jobs:
  run-tests:
    name: Run Selenium Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3  # Checkout the repository code

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'corretto'  # Use Corretto JDK

      - name: Install Maven
        run: |
          sudo apt-get update
          sudo apt-get install -y maven  # Install Maven

      - name: Build with Maven
        run: mvn clean install  # Build Maven project

      - name: Run Selenium Tests
        run: mvn test -DsuiteXmlFile=testng.xml  # Run TestNG tests with Maven

      - name: Archive test results
        if: always()  # Always execute this step, even if previous steps failed
        uses: actions/upload-artifact@v2
        with:
          name: testng-test-results
          path: target/surefire-reports  # Path to TestNG test results
