name: TEST-NG-01

on:
  workflow_dispatch:

jobs:
  test:
    name: Selenium Tests
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: 11

    - name: Build with Maven
      run: mvn clean install

    - name: Run Selenium Tests
      run: mvn test -DsuiteXmlFile=testng.xml
